service: s3-file-uploadapi

provider:
  name: aws
  runtime: nodejs14.x
  stage: dev
  region: ap-south-1
  apiName: ${self:service}
  memorySize: 128
  timeout: 10
  # enviroment:
  #   FILE_UPLOAD_BUCKET_NAME: ${self:custom.fileBucketName}

plugins:
  - serverless-iam-roles-per-function
custom:
  fileBucketName: s3-file-bucket-bik-${self:provider.stage}

functions:
  s3FileUploader:
    handler: src/upload.handler
    name: s3-file-uploader-bik
    events:
      - http:
          path: file
          method: POST
    iamRoleStatements:
      - Effect: Allow
        Action:
          - "s3::Put*"
        Resource: arn:aws:s3:::${self:custom.fileBucketName}/*
resources:
  Resources:
    FileBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:custom.fileBucketName}
        AccessControl: Private
    NewSQSQueue:
      Type: "AWS::SQS::Queue"
      Properties:
        QueueName: sqs-queue-${opt:stage, self:provider.stage}.fifo
        FifoQueue: true
